default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: dev
  password: amperor123

development:
  <<: *default
  database: logintoblogdev

test:
  <<: *default
  database: logintoblogtest

production:
  <<: *default
  database: logintoblogprod
